runtime: nodejs18

env: standard

handlers:
- url: /.*
  script: auto

env_variables:
  MONGODB_URI: "mongodb+srv://${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_CLUSTER}/pos"
  JWT_SECRET: "${JWT_SECRET}"
  NODE_ENV: "production"
