directories:
  output: dist-electron
  buildResources: resources
appId: com.restaurant.pos
productName: Restaurant POS
files:
  - filter:
      - electron/**/*
      - package.json
extraResources:
  - from: backend/dist
    to: backend/dist
  - from: frontend/dist
    to: frontend/dist
  - from: resources/mongod
    to: mongod
    filter:
      - '**/*'
win:
  icon: resources/icon.ico
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Restaurant POS
  license: resources/license.txt
  include: resources/installer.nsh
asar: true
asarUnpack:
  - node_modules/**/*
electronVersion: 42.0.1
